- name: Run PostgreSQL container
  docker_container:
    name: database
    image: elishama07/tp-devops-database
    pull: true
    networks:
      - name: "app-network"
    env:
      POSTGRES_USER: "{{POSTGRES_USER}}"
      POSTGRES_PASSWORD: "{{POSTGRES_PASSWORD}}"
      POSTGRES_DB: "{{POSTGRES_DB}}"

    state: started